NUM_SEEDS: 1
SEED: 0
HYP_TUNE: false
ENTITY: ''
PROJECT: ''
WANDB_MODE: offline
WANDB_LOG_ALL_SEEDS: false
SAVE_PATH: D:/omp/MainSearch/explore/benchmark_suitability_smax/smoke_models
alg:
  TOTAL_TIMESTEPS: 8192
  NUM_ENVS: 2
  NUM_STEPS: 32
  BUFFER_SIZE: 512
  BUFFER_BATCH_SIZE: 8
  HIDDEN_SIZE: 64
  MIXER_EMBEDDING_DIM: 16
  MIXER_HYPERNET_HIDDEN_DIM: 32
  MIXER_INIT_SCALE: 0.001
  EPS_START: 1.0
  EPS_FINISH: 0.05
  EPS_DECAY: 0.1
  MAX_GRAD_NORM: 10
  TARGET_UPDATE_INTERVAL: 10
  TAU: 1.0
  NUM_EPOCHS: 1
  LR: 5.0e-05
  LEARNING_STARTS: 512
  LR_LINEAR_DECAY: false
  GAMMA: 0.99
  REW_SCALE: 10.0
  ENV_NAME: HeuristicEnemySMAX
  MAP_NAME: smacv2_5_units
  ENV_KWARGS:
    see_enemy_actions: true
    walls_cause_death: true
    attack_mode: closest
  TEST_DURING_TRAINING: true
  TEST_INTERVAL: 0.2
  TEST_NUM_STEPS: 128
  TEST_NUM_ENVS: 16
TOTAL_TIMESTEPS: 8192
NUM_ENVS: 2
NUM_STEPS: 32
BUFFER_SIZE: 512
BUFFER_BATCH_SIZE: 8
HIDDEN_SIZE: 64
MIXER_EMBEDDING_DIM: 16
MIXER_HYPERNET_HIDDEN_DIM: 32
MIXER_INIT_SCALE: 0.001
EPS_START: 1.0
EPS_FINISH: 0.05
EPS_DECAY: 0.1
MAX_GRAD_NORM: 10
TARGET_UPDATE_INTERVAL: 10
TAU: 1.0
NUM_EPOCHS: 1
LR: 5.0e-05
LEARNING_STARTS: 512
LR_LINEAR_DECAY: false
GAMMA: 0.99
REW_SCALE: 10.0
ENV_NAME: HeuristicEnemySMAX
MAP_NAME: smacv2_5_units
ENV_KWARGS:
  see_enemy_actions: true
  walls_cause_death: true
  attack_mode: closest
TEST_DURING_TRAINING: true
TEST_INTERVAL: 0.2
TEST_NUM_STEPS: 128
TEST_NUM_ENVS: 16
NUM_UPDATES: 128
